apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-order
  labels:
    app: pet-order
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-order
  template:
    metadata:
      labels:
        app: pet-order
    spec:
      containers:
        - name: pet-order
          image: aditisri1311/pet_order:latest
          ports:
            - containerPort: 8001
          env:
            - name: DEBUG
              value: "true"
            - name: DB_HOST
              value: "wj48254.central-india.azure"
            - name: DB_NAME
              value: "pet_db"
            - name: DB_SCHEMA
              value: "pet_schema1"
            - name: DB_WAREHOUSE
              value: "pet_dw"
            - name: DB_USER
              value: "TanviiSahuu"
            - name: DB_PASSWORD
              value: "Snowflake@2025"